// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7 reads the seed command from here, NOT from package.json's
    // "prisma" key (that key is ignored once prisma.config.ts exists). This is
    // what makes `prisma db seed` (and `migrate reset`) run the seed.
    seed: "tsx -r dotenv/config prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
